const { DataTypes } = require('sequelize');

module.exports = (sequelize) => sequelize.define('NiparTotal25', {
  id: { type: DataTypes.INTEGER, primaryKey: true, autoIncrement: true },
  ranking: DataTypes.INTEGER,
  dte_nifap: DataTypes.BIGINT,
  parc_num: DataTypes.INTEGER,
  sub_parc_num: DataTypes.INTEGER,
  cul_id: DataTypes.BIGINT,
  cod_cult_decl1: DataTypes.STRING(20),
  unit_amount: DataTypes.DECIMAL(12, 4),
  area_decl1: DataTypes.DECIMAL(12, 4),
  unit_amount_grp: DataTypes.DECIMAL(12, 4),
  balde: DataTypes.STRING(20),
  recolhido: { type: DataTypes.BOOLEAN, defaultValue: false },
  selecao: DataTypes.STRING(20),
  area_gsa: DataTypes.DECIMAL(12, 4),
  obs_gsa: DataTypes.TEXT,
  gsa_qa: DataTypes.STRING(5),
  area_cf: DataTypes.DECIMAL(12, 4),
  obs_ams: DataTypes.TEXT,
  ams_qa: DataTypes.STRING(5),
  obs_ccampo: DataTypes.TEXT,
  ccampo_aval: DataTypes.STRING(5),
  obs_crits_ca: DataTypes.TEXT,
  crits_ca_aval: DataTypes.STRING(5),
  obs_crits_cc: DataTypes.TEXT,
  crits_cc_aval: DataTypes.STRING(5),
  obs_encab: DataTypes.TEXT,
  encab_aval: DataTypes.STRING(5),
  out_crits: DataTypes.TEXT,
  ua_fta: DataTypes.DECIMAL(12, 4),
  sin_fta: DataTypes.STRING(5),
  ua_maa: DataTypes.DECIMAL(12, 4),
  sin_maa: DataTypes.STRING(5),
  ua_eco: DataTypes.DECIMAL(12, 4),
  sin_eco: DataTypes.STRING(5),
  sin_mzd: DataTypes.STRING(5),
  sin_aas: DataTypes.STRING(5),
  sin_pdi: DataTypes.STRING(5),
  covered: DataTypes.BOOLEAN,
  smo_result: DataTypes.STRING(5),
  nome_tec_atrib: DataTypes.STRING(100),
  satisfaz_area: DataTypes.BOOLEAN,
  dat_alt: DataTypes.DATE,
  nome_uti_alt: DataTypes.STRING(100)
}, { tableName: 'grp_nipar_total_25', timestamps: false });
